name: Plugin Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Grant executable permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew pluginJar

      - name: Upload the plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: ChunkyDenoiser
          path: build/libs/*.jar
          if-no-files-found: error
